version: "3"

services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.21
    restart: always 
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "443:443/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "3300:3000/tcp"
      - "3380:80/tcp"
    volumes:
       - ${DATADIR}/adguard/workdir:/opt/adguardhome/work
       - ${DATADIR}/adguard/confdir:/opt/adguardhome/conf
    cap_add:
      - NET_ADMIN
    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "200m"

  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:7.3.76
    container_name: unifi-controller
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MEM_LIMIT=2048M #optional
    volumes:
      - ${DATADIR}/unifi-controller:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "200m"

  whatsupdocker:
    image: fmartinou/whats-up-docker:6.0.1
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3000
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/fmartinou/whats-up-docker/releases/tag/$${major}.$${minor}.$${patch}'
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "200m"

  loki:
    container_name: loki
    image: grafana/loki:main
    restart: always
    ports:
      - 3100:3100
    volumes:
      - ${DATADIR}/loki/config/loki-config.yaml:/etc/loki/loki-config.yaml
      - ${DATADIR}/loki/data:/data/loki
    command: "-config.file=/etc/loki/loki-config.yaml"
    labels:
      - 'wud.tag.include=main'
      - 'wud.watch.digest=true'
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "200m"