version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    restart: always
    user: ${PUID}:${PGID}
    ports:
      - "9090:9090"
    volumes:
      - ${DATADIR}/prometheus/etc:/etc/prometheus
      - ${DATADIR}/prometheus/data:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "10m"

  node_exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'
    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "10m"

  cadvisor:
    image: zcube/cadvisor:v0.45.0
    container_name: cadvisor
    command:
      - "--docker_only=true"
      - "--housekeeping_interval=30s"
      - "--disable_metrics=accelerator,cpu_topology,disk,memory_numa,tcp,udp,percpu,sched,process,hugetlb,referenced_memory,resctrl,cpuset,advtcp,memory_numa"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
    devices:
      - /dev/kmsg
    restart: always
    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "10m"
