version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    restart: always
    volumes:
      - ${DATADIR}/mosquitto/config:/mosquitto/config/
      - ${DATADIR}/mosquitto/data:/mosquitto/data
      - ${DATADIR}/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'

  grafana:
    image: grafana/grafana:main-ubuntu
    restart: always
    volumes:
      - ${DATADIR}/grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - TZ=${TZ}
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    labels:
      - 'wud.tag.include=main-ubuntu'
      - 'wud.watch.digest=true'

  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:0.11.1
    privileged: true
    restart: always
    shm_size: "64mb"
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATADIR}/frigate/config.yml:/config/config.yml:ro
      - ${DARADIR}/firgate/disk:/db
      - ${DATADIR}/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      - TZ=${TZ}
      - FRIGATE_RTSP_PASSWORD="frigateRTSP"
      - LIBVA_DRIVER_NAME="radeonsi"
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'

  zwavejsui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:8.6.2
    restart: always
    tty: true
    stop_signal: SIGINT
    depends_on:
      mosquitto:
        condition: service_started
    environment:
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=${TZ}
    devices:
      - '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_61201AE6-if00-port0:/dev/zwave'
    volumes:
      - ${DATADIR}/zwavejs/store:/usr/src/app/store
    ports:
      - 8091:8091
      - 3002:3000
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2022.12.8
    restart: always
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1
    volumes:
      - ${DATADIR}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    privileged: true
    depends_on:
      mosquitto:
        condition: service_started
      frigate:
        condition: service_started
      grafana:
        condition: service_started
      zwavejs:
        condition: service_started
    ports:
      - 8123:8123
    environment:
      - TZ=${TZ}
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/home-assistant/core/releases/tag/$${major}.$${minor}.$${patch}'
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "500m"